#!/usr/bin/env python3
"""Render preview PNG figures from rollout CSV files.

This is a quick visual check layer for the LaTeX figures. It reads the CSVs
generated by `build_rollout_latex.py` and saves one PNG per dataset/metric.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

import matplotlib.pyplot as plt

DEFAULT_ROOT = Path(__file__).resolve().parent
TITLE_SIZE = 20
LABEL_SIZE = 16
TICK_SIZE = 12
LEGEND_SIZE = 11

STYLE_MAP = {
    "srno": {
        "label": "SRNO",
        "color": "#1F77B4",
        "linestyle": "-",
        "linewidth": 2.0,
    },
    "edsr": {
        "label": "EDSR",
        "color": "#0F766E",
        "linestyle": "--",
        "linewidth": 2.0,
    },
    "basicvsrpp": {
        "label": "BasicVSR++",
        "color": "#FF7F0E",
        "linestyle": "-.",
        "linewidth": 2.0,
    },
    "rvrt": {
        "label": "RVRT",
        "color": "#7E57C2",
        "linestyle": (0, (4, 2)),
        "linewidth": 2.0,
    },
    "vrt": {
        "label": "VRT",
        "color": "#2CA02C",
        "linestyle": (0, (4, 1.5, 1, 1.5)),
        "linewidth": 2.0,
    },
    "sdift": {
        "label": "SDIFT",
        "color": "#6B7280",
        "linestyle": "-",
        "linewidth": 2.0,
    },
    "wdno": {
        "label": "WDNO",
        "color": "#C2185B",
        "linestyle": "--",
        "linewidth": 2.0,
    },
    "resshift50m": {
        "label": "ResShift",
        "color": "#8C564B",
        "linestyle": "-",
        "linewidth": 2.2,
    },
    "wrd": {
        "label": "WRD",
        "color": "#D62728",
        "linestyle": (0, (4, 1.5, 1, 1.5)),
        "linewidth": 2.2,
    },
    "wrd_kcs_wsdf": {
        "label": "WRD",
        "color": "#111111",
        "linestyle": "-",
        "linewidth": 2.8,
    },
}

METRIC_META = {
    "error": {
        "ylabel": "Mean absolute error",
        "title": "Error over time",
    },
    "rmse": {
        "ylabel": "RMSE",
        "title": "RMSE over time",
    },
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    parser.add_argument("--dpi", type=int, default=220)
    return parser.parse_args()


def read_manifest(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def read_csv(path: Path) -> tuple[list[int], dict[str, list[float]]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        frame_idx: list[int] = []
        series: dict[str, list[float]] = {k: [] for k in reader.fieldnames if k != "frame_idx"}
        for row in reader:
            frame_idx.append(int(row["frame_idx"]))
            for key in series:
                series[key].append(float(row[key]))
    return frame_idx, series


def render_one(
    png_path: Path,
    dataset_title: str,
    metric_key: str,
    frame_idx: list[int],
    series: dict[str, list[float]],
) -> None:
    meta = METRIC_META[metric_key]
    all_values = [v for curve in series.values() for v in curve]
    max_val = max(all_values)
    pad_factor = 1.30 if dataset_title.startswith(("ERA5", "KF256")) else 1.16

    fig, ax = plt.subplots(figsize=(11.4, 6.3))
    for key, values in series.items():
        style = STYLE_MAP[key]
        ax.plot(
            frame_idx,
            values,
            label=style["label"],
            color=style["color"],
            linestyle=style["linestyle"],
            linewidth=style["linewidth"],
        )

    ax.set_xlabel("Frame index", fontsize=LABEL_SIZE, fontweight="bold")
    ax.set_ylabel(meta["ylabel"], fontsize=LABEL_SIZE, fontweight="bold")
    ax.set_xlim(frame_idx[0], frame_idx[-1])
    ax.set_ylim(0, max_val * pad_factor)
    ax.set_axisbelow(True)
    ax.grid(True, which="major", linestyle="--", linewidth=0.9, alpha=0.35)
    ax.grid(True, which="minor", linestyle=":", linewidth=0.65, alpha=0.18)
    ax.minorticks_on()
    ax.tick_params(labelsize=TICK_SIZE, width=1.0, length=5)
    for label in ax.get_xticklabels() + ax.get_yticklabels():
        label.set_fontweight("bold")
    for spine in ax.spines.values():
        spine.set_linewidth(1.0)
    ax.legend(
        loc="upper right",
        bbox_to_anchor=(0.985, 0.985),
        ncol=2,
        frameon=True,
        facecolor="white",
        edgecolor="#d0d0d0",
        framealpha=0.92,
        fontsize=LEGEND_SIZE,
        prop={"weight": "bold", "size": LEGEND_SIZE},
        handlelength=2.6,
        columnspacing=0.9,
        borderpad=0.45,
        labelspacing=0.45,
    )

    fig.tight_layout()
    fig.savefig(png_path, dpi=args.dpi, bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    root = args.root
    data_dir = root / "data"
    png_dir = root / "png"
    manifest_path = root / "manifest.json"

    png_dir.mkdir(parents=True, exist_ok=True)
    manifest = read_manifest(manifest_path)

    for dataset_name, dataset_meta in manifest.items():
        dataset_title = dataset_meta["dataset_title"]
        for metric_key in METRIC_META:
            csv_path = data_dir / f"{dataset_name.lower()}_{metric_key}_over_time.csv"
            frame_idx, series = read_csv(csv_path)
            png_path = png_dir / f"{dataset_name.lower()}_{metric_key}_over_time.png"
            render_one(
                png_path=png_path,
                dataset_title=dataset_title,
                metric_key=metric_key,
                frame_idx=frame_idx,
                series=series,
            )
            print(f"Saved: {png_path}")


if __name__ == "__main__":
    args = parse_args()
    main()
