model:
  name: 'FNO2d'
  modes1: [15, 12, 9, 9, 9]
  modes2: [15, 12, 9, 9, 9]
  width: 64
  fc_dim: 128
  layers: [16, 24, 24, 32, 32]
  in_dim: 1
  out_dim: 1
  act: 'gelu'
  pos_dim: 2
  upsample_factor: [4, 4]

data:
  name: 'KolmogorovFlow'
  hr_path: '/data1/user/yc/NeurIPS26_Fluid_VSR/dataset/KF256_data/x4/HR'
  lr_path: '/data1/user/yc/NeurIPS26_Fluid_VSR/dataset/KF256_data/x4/LR'
  num_samples: 70            # 70 trajectories × 180 frames = 12,600 frames
  sample_factor: 4
  shape: [256, 256]
  use_input_frame: False     # only use 'output' frames, skip 'input' initial condition
  train_batchsize: 64
  eval_batchsize: 64
  train_ratio: 0.8           # 56 trajectories = 10,080 frames
  valid_ratio: 0.1           # 7 trajectories = 1,260 frames
  test_ratio: 0.1            # 7 trajectories = 1,260 frames
  normalize: True
  normalizer_type: 'PGN'

train:
  random_seed: 42
  cuda: True
  device: 0
  epochs: 500
  patience: 10
  eval_freq: 5
  saving_best: True
  load_ckpt: False
  saving_ckpt: True
  ckpt_freq: 5
  ckpt_max: 5
  distribute: False
  distribute_mode: 'DDP'
  device_ids: [0, 1, 2, 3]

optimize:
  optimizer: 'AdamW'
  lr: 0.001
  weight_decay: 0.001

schedule:
  scheduler: 'StepLR'
  step_size: 300
  gamma: 0.5

  # scheduler: 'OneCycleLR'
  # div_factor: 25
  # final_div_factor: 100
  # pct_start: 0.3
  # steps_per_epoch: 39 #计算公式，ceil(training_data_size / train_batch_size)：ceil(9800 / 256) = 39

log:
  verbose: True
  log: True
  log_dir: '/data1/user/yc/NeurIPS26_Fluid_VSR/code/DiffSR-main/logs/KolmogorovFlow/FNO'
  wandb: True
  wandb_project: 'DiffVSR-FNO2d-KolmogorovFlow'

